// Generated by gencpp from file pangyo_control/figure.msg
// DO NOT EDIT!


#ifndef PANGYO_CONTROL_MESSAGE_FIGURE_H
#define PANGYO_CONTROL_MESSAGE_FIGURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pangyo_control
{
template <class ContainerAllocator>
struct figure_
{
  typedef figure_<ContainerAllocator> Type;

  figure_()
    : figure()  {
    }
  figure_(const ContainerAllocator& _alloc)
    : figure(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _figure_type;
  _figure_type figure;





  typedef boost::shared_ptr< ::pangyo_control::figure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pangyo_control::figure_<ContainerAllocator> const> ConstPtr;

}; // struct figure_

typedef ::pangyo_control::figure_<std::allocator<void> > figure;

typedef boost::shared_ptr< ::pangyo_control::figure > figurePtr;
typedef boost::shared_ptr< ::pangyo_control::figure const> figureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pangyo_control::figure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pangyo_control::figure_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pangyo_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'HasHeader': False, 'IsMessage': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pangyo_control': ['/home/choiys/stauto_ws/src/stauto_sensor/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pangyo_control::figure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pangyo_control::figure_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pangyo_control::figure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pangyo_control::figure_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pangyo_control::figure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pangyo_control::figure_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pangyo_control::figure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5aeb03f16c36d602af577d480cad4dd3";
  }

  static const char* value(const ::pangyo_control::figure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5aeb03f16c36d602ULL;
  static const uint64_t static_value2 = 0xaf577d480cad4dd3ULL;
};

template<class ContainerAllocator>
struct DataType< ::pangyo_control::figure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pangyo_control/figure";
  }

  static const char* value(const ::pangyo_control::figure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pangyo_control::figure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] figure\n\
";
  }

  static const char* value(const ::pangyo_control::figure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pangyo_control::figure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.figure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct figure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pangyo_control::figure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pangyo_control::figure_<ContainerAllocator>& v)
  {
    s << indent << "figure[]" << std::endl;
    for (size_t i = 0; i < v.figure.size(); ++i)
    {
      s << indent << "  figure[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.figure[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANGYO_CONTROL_MESSAGE_FIGURE_H
